import type {
  ProviderWeatherSnapshot,
  WeatherCapabilityMap,
} from '@/modules/weather/providers/types'
import type { WeatherLocation, WeatherSnapshot } from '@/modules/weather/types/weather'

export const weatherLocation: WeatherLocation = {
  id: 101,
  name: 'Test City',
  kind: 'Locality',
  admin1: 'Test Region',
  country: 'Test Country',
  countryCode: 'TC',
  latitude: 34,
  longitude: 114,
  elevation: 80,
  timezone: 'Asia/Shanghai',
  displayLabel: 'Test City, Test Region, Test Country',
  source: 'openMeteo',
}

export const xiaomiWeatherLocation: WeatherLocation = {
  id: 'xiaomi:opaque-location',
  name: 'Test City',
  kind: 'Location',
  admin1: 'Test Region',
  country: 'Test Country',
  countryCode: '',
  latitude: 34,
  longitude: 114,
  elevation: null,
  timezone: 'auto',
  displayLabel: 'Test City, Test Region, Test Country',
  providerLocationIds: { xiaomi: 'opaque-location' },
}

export const capabilities: WeatherCapabilityMap = {
  current: 'available',
  hourly: 'available',
  daily: 'available',
  aqi: 'available',
  minutely: 'empty-array',
  alerts: 'empty-array',
  indices: 'available',
  typhoon: 'empty-array',
  yesterday: 'available',
  preHour: 'available',
  sourceMaps: 'available',
  brandInfo: 'available',
  updateTime: 'available',
}

export function createLegacySnapshot(
  provider: WeatherSnapshot['provider'] = 'openMeteo',
): WeatherSnapshot {
  return {
    provider,
    location: { ...weatherLocation },
    timezone: 'Asia/Shanghai',
    timezoneAbbreviation: 'GMT+8',
    fetchedAt: '2026-07-14T01:00:00.000Z',
    current: {
      time: '2026-07-14T01:00:00.000Z',
      temperature: 0,
      apparentTemperature: -1,
      relativeHumidity: 50,
      precipitation: 0,
      rain: 0,
      showers: 0,
      snowfall: 0,
      cloudCover: 20,
      windSpeed: 0,
      windDirection: 0,
      windGusts: 0,
      uvIndex: 0,
      pressure: 1000,
      visibility: 10,
      isDay: true,
      condition: { code: 0, label: 'Clear sky', shortLabel: 'Clear' },
    },
    hourly: [{
      time: '2026-07-14T01:00:00.000Z',
      temperature: 0,
      apparentTemperature: -1,
      precipitationProbability: 0,
      precipitation: 0,
      windSpeed: 0,
      windGusts: 0,
      uvIndex: 0,
      isDay: true,
      condition: { code: 0, label: 'Clear sky', shortLabel: 'Clear' },
    }],
    daily: [{
      date: '2026-07-14',
      temperatureMax: 5,
      temperatureMin: -2,
      apparentTemperatureMax: 4,
      apparentTemperatureMin: -3,
      precipitationSum: 0,
      precipitationProbabilityMax: 0,
      windSpeedMax: 5,
      windDirectionDominant: 0,
      windGustsMax: 8,
      uvIndexMax: 1,
      sunrise: '2026-07-14T00:00:00.000Z',
      sunset: '2026-07-14T12:00:00.000Z',
      condition: { code: 0, label: 'Clear sky', shortLabel: 'Clear' },
    }],
    shortTermPrecipitation: null,
    alerts: [],
    providerCapabilities: { alerts: false, visibility: true, airQuality: true },
    units: {
      temperature: '°C',
      precipitation: 'mm',
      probability: '%',
      windSpeed: 'km/h',
      humidity: '%',
      uvIndex: '',
      pressure: 'hPa',
      visibility: 'km',
    },
    advice: { items: [], notes: [] },
  }
}

export function createXiaomiProviderSnapshot(): ProviderWeatherSnapshot {
  return {
    provider: 'xiaomi',
    location: {
      provider: 'xiaomi',
      providerLocationId: 'opaque-location',
      name: 'Test City',
      administrativeArea: 'Test Region',
      country: 'Test Country',
      latitude: 34,
      longitude: 114,
    },
    updatedAt: '2026-07-14T01:00:00.000Z',
    current: {
      observedAt: '2026-07-14T01:00:00.000Z',
      temperatureC: 0,
      apparentTemperatureC: -1,
      humidityPercent: 50,
      windSpeedKmh: 0,
      windDirectionDegrees: 0,
      pressureHpa: 1000,
      visibilityKm: 10,
      uvIndex: 0,
      condition: { id: 'clear', providerCode: '0' },
    },
    hourly: [{
      time: '2026-07-14T01:00:00.000Z',
      temperatureC: 0,
      condition: { id: 'clear', providerCode: '0' },
    }],
    daily: [{
      date: '2026-07-14',
      temperatureMaxC: 5,
      temperatureMinC: -2,
      dayCondition: { id: 'clear', providerCode: '0' },
      nightCondition: { id: 'clear', providerCode: '0' },
      sunrise: '2026-07-14T00:00:00.000Z',
      sunset: '2026-07-14T12:00:00.000Z',
    }],
    airQuality: { value: 42, scale: 'unknown' },
    capabilities: { ...capabilities },
    units: {
      temperature: 'celsius',
      windSpeed: 'kilometres-per-hour',
      windDirection: 'degrees',
      humidity: 'percent',
      pressure: 'hectopascals',
      visibility: 'kilometres',
    },
    extensions: { alerts: [], minutely: null },
    diagnostics: [],
  }
}
